--USE master;
--GO

--CREATE DATABASE BdGenesis;
--GO

--USE BdGenesis;
--GO

CREATE TABLE Sucursal
(
Codigo INT NOT NULL PRIMARY KEY,
Ciudad VARCHAR(50) NOT NULL,
Region VARCHAR(50) NOT NULL,
Objetivo MONEY,
Ventas MONEY NOT NULL,
Director INT NOT NULL,
);
GO

CREATE TABLE Vendedor
(
DNI INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Edad TINYINT NOT NULL,
Cargo VARCHAR(50) NOT NULL,
Contrato DATETIME NOT NULL,
Ventas MONEY NOT NULL,
Sucursal INT,  
Director INT,
);
GO

CREATE TABLE Producto
(
Marca VARCHAR(50) NOT NULL,
Modelo VARCHAR(50) NOT NULL,
Descripcion VARCHAR(999) NOT NULL, -- Descripcion
FTecnical VARCHAR(999) NOT NULL,
Precio MONEY NOT NULL,
Stock INT NOT NULL,
Foto IMAGE,
PRIMARY KEY(Marca, Modelo)
);
GO

CREATE TABLE Cliente
(
DNI INT NOT NULL PRIMARY KEY,
NIT BIGINT NOT NULL,    
Nombre VARCHAR(50) NOT NULL,
Email VARCHAR(50),
Direccion VARCHAR(100),
Celular INT,
RepVentas INT NOT NULL,
);
GO

CREATE TABLE Venta
(
Nrofactura INT NOT NULL PRIMARY KEY,
Fecha DATETIME NOT NULL,
Total MONEY NOT NULL,
Cliente INT NOT NULL,
Vendedor INT NOT NULL,
);  
GO

CREATE TABLE Detallev
(
Factura INT NOT NULL,
MarcaP VARCHAR(50) NOT NULL,
ModeloP VARCHAR(50) NOT NULL,
PrecioU MONEY NOT NULL,
Cantidad INT NOT NULL,
Importe MONEY NOT NULL,
PRIMARY KEY(Factura, MarcaP, Modelop)
);
GO

ALTER TABLE Sucursal
ADD CONSTRAINT Dirige FOREIGN KEY (Director) REFERENCES Vendedor(DNI);
GO

ALTER TABLE Detallev 
ADD CONSTRAINT Vdetalle FOREIGN KEY(Factura) REFERENCES Venta(Nrofactura); 
GO

ALTER TABLE Detallev
ADD CONSTRAINT PDetalle FOREIGN KEY(MarcaP, ModeloP) REFERENCES Producto(Marca, Modelo);
GO

ALTER TABLE Venta
ADD CONSTRAINT Realiza FOREIGN KEY (Vendedor) REFERENCES Vendedor(DNI);
GO

ALTER TABLE Venta
ADD CONSTRAINT Efectua FOREIGN KEY (Cliente) REFERENCES Cliente(DNI);
GO

ALTER TABLE Cliente
ADD CONSTRAINT Atiende FOREIGN KEY (RepVentas) REFERENCES Vendedor(DNI);
GO

ALTER TABLE Vendedor
ADD CONSTRAINT Trabajan FOREIGN KEY (Sucursal) REFERENCES Sucursal(Codigo);
GO

ALTER TABLE Vendedor
ADD CONSTRAINT Director FOREIGN KEY (Director) REFERENCES Vendedor(DNI);
GO

--DROP DATABASE BdGenesis;