-- PRACTICAS LIBRO SQL SERVER

USE master;
GO
CREATE DATABASE Ferias
ON
PRIMARY
(
NAME = Ferias,
FILENAME = 'F:\Mis Documentos\CURSOS\PROGRAMING\SQL\PRACTICE DATA BASES\Ferias.mdf',
SIZE = 3MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1MB
)
LOG ON
(
NAME = Ferias_log,
FILENAME = 'F:\Mis Documentos\CURSOS\PROGRAMING\SQL\PRACTICE DATA BASES\Ferias_log.ldf',
SIZE = 1MB,
MAXSIZE = 100MB,
FILEGROWTH = 10%
);
GO

ALTER DATABASE Ferias
ADD LOG FILE
(
NAME = Ferias1_log,
FILENAME = 'F:\Mis Documentos\CURSOS\PROGRAMING\SQL\PRACTICE DATA BASES\Feria1_log.ldf',
SIZE = 1MB,
MAXSIZE = 50MB,
FILEGROWTH = 10%
);
GO

ALTER DATABASE Ferias
ADD LOG FILE
(
NAME = Ferias2_log,
FILENAME = 'F:\Mis Documentos\CURSOS\PROGRAMING\SQL\PRACTICE DATA BASES\Feria2_log.ldf',
SIZE = 1MB,
MAXSIZE = 50MB,
FILEGROWTH = 10%
);
GO

use Ferias

ALTER DATABASE Ferias
REMOVE FILE Ferias1_log
GO


--DROP DATABASE Ferias;